import type {PlainObject, Simplify} from '@oscarpalmer/atoms/models';
import type {Schema} from '../schema';
import type {OptionalKeys, RequiredKeys} from './misc.model';
import type {PropertyValidators} from './schematic.plain.model';
import type {ToSchemaPropertyType, ToSchemaType} from './transform.model';

/**
 * A typed optional property definition generated by {@link TypedSchematic} for optional keys, with `$required` set to `false` and excludes `undefined` from the type
 *
 * @template Value Property's type _(including `undefined`)_
 *
 * @example
 * ```ts
 * // For `{ name?: string }`, the `name` key produces:
 * // TypedPropertyOptional<string | undefined>
 * // => { $required: false; $type: 'string'; ... }
 * ```
 */
export type TypedPropertyOptional<Value> = {
	$default?: never;
	$required: false;
	$type: ToSchemaPropertyType<Exclude<Value, undefined>>;
	$validators?: PropertyValidators<ToSchemaPropertyType<Exclude<Value, undefined>>>;
};

/**
 * A typed required property definition generated by {@link TypedSchematic} for required keys, with `$required` defaulting to `true`
 *
 * @template Value Property's type
 *
 * @example
 * ```ts
 * // For `{ name: string }`, the `name` key produces:
 * // TypedPropertyRequired<string>
 * // => { $required?: true; $type: 'string'; ... }
 * ```
 */
export type TypedPropertyRequired<Value> = {
	$default?: unknown;
	$required?: true;
	$type: ToSchemaPropertyType<Value>;
	$validators?: PropertyValidators<ToSchemaPropertyType<Value>>;
};

/**
 * Creates a schema type constrained to match a TypeScript type
 *
 * Required keys map to {@link ToSchemaType} or {@link TypedPropertyRequired}; plain object values may also use {@link Schema}
 *
 * @template Model Object type to generate a schema for
 *
 * @example
 * ```ts
 * type User = { name: string; age: number; bio?: string };
 *
 * const schema: TypedSchema<User> = {
 *   name: 'string',
 *   age: 'number',
 *   bio: { $required: false, $type: 'string' },
 * };
 * ```
 */
export type TypedSchematic<Model extends PlainObject> = Simplify<
	{
		[Key in RequiredKeys<Model>]: Model[Key] extends PlainObject
			? Schema<Model[Key]>
			: ToSchemaType<Model[Key]> | TypedPropertyRequired<Model[Key]>;
	} & {
		[Key in OptionalKeys<Model>]: Exclude<Model[Key], undefined> extends PlainObject
			? Schema<Exclude<Model[Key], undefined>>
			: TypedPropertyOptional<Model[Key]>;
	}
>;
