import type {PlainObject, Simplify} from '@oscarpalmer/atoms/models';
import type {Schematic} from '../schematic';
import type {OptionalKeys, RequiredKeys} from './misc.model';
import type {ToSchemaPropertyType, ToSchemaType} from './transform.model';
import type {PropertyValidators} from './validation.model';

/**
 * A typed optional property definition generated by {@link TypedSchema} for optional keys, with `$required` set to `false` and excludes `undefined` from the type
 *
 * @template Value - Property's type _(including `undefined`)_
 *
 * @example
 * ```ts
 * // For `{ name?: string }`, the `name` key produces:
 * // TypedPropertyOptional<string | undefined>
 * // => { $required: false; $type: 'string'; ... }
 * ```
 */
export type TypedPropertyOptional<Value> = {
	/**
	 * The property is not required
	 */
	$required: false;
	/**
	 * The type(s) of the property
	 */
	$type: ToSchemaPropertyType<Exclude<Value, undefined>>;
	/**
	 * Custom validators for the property and its types
	 */
	$validators?: PropertyValidators<ToSchemaPropertyType<Exclude<Value, undefined>>>;
};

/**
 * A typed required property definition generated by {@link TypedSchema} for required keys, with `$required` defaulting to `true`
 *
 * @template Value - Property's type
 *
 * @example
 * ```ts
 * // For `{ name: string }`, the `name` key produces:
 * // TypedPropertyRequired<string>
 * // => { $required?: true; $type: 'string'; ... }
 * ```
 */
export type TypedPropertyRequired<Value> = {
	/**
	 * The property is required _(defaults to `true`)_
	 */
	$required?: true;
	/**
	 * The type(s) of the property
	 */
	$type: ToSchemaPropertyType<Value>;
	/**
	 * Custom validators for the property and its types
	 */
	$validators?: PropertyValidators<ToSchemaPropertyType<Value>>;
};

/**
 * Creates a schema type constrained to match a TypeScript type
 *
 * Required keys map to {@link ToSchemaType} or {@link TypedPropertyRequired}; plain object values may also use {@link Schematic}. Optional keys map to {@link TypedPropertyOptional} or, for plain objects, {@link TypedSchemaOptional}
 *
 * @template Model - Object type to generate a schema for
 *
 * @example
 * ```ts
 * type User = { name: string; age: number; bio?: string };
 *
 * const schema: TypedSchema<User> = {
 *   name: 'string',
 *   age: 'number',
 *   bio: { $required: false, $type: 'string' },
 * };
 * ```
 */
export type TypedSchema<Model extends PlainObject> = Simplify<
	{
		[Key in RequiredKeys<Model>]: Model[Key] extends PlainObject
			? TypedSchemaRequired<Model[Key]> | Schematic<Model[Key]>
			: ToSchemaType<Model[Key]> | TypedPropertyRequired<Model[Key]>;
	} & {
		[Key in OptionalKeys<Model>]: Exclude<Model[Key], undefined> extends PlainObject
			?
					| TypedSchemaOptional<Exclude<Model[Key], undefined>>
					| Schematic<Exclude<Model[Key], undefined>>
			: TypedPropertyOptional<Model[Key]>;
	}
>;

/**
 * A {@link TypedSchema} variant for optional nested objects, with `$required` fixed to `false`
 *
 * @template Model - Nested object type
 */
type TypedSchemaOptional<Model extends PlainObject> = {
	$required: false;
} & TypedSchema<Model>;

/**
 * A {@link TypedSchema} variant for required nested objects, with `$required` defaulting to `true`
 *
 * @template Model - Nested object type
 */
type TypedSchemaRequired<Model extends PlainObject> = {
	$required?: true;
} & TypedSchema<Model>;
